language: node_js
node_js:
  - node
services:
  - docker
cache: npm

script:
  - docker build . -t piedfront

addons:
  ssh_known_hosts: 34.90.231.206

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - docker save piedfront | bzip2 | ssh piedpiper@34.90.231.206 'bunzip2 | docker load && sudo docker stop front && sudo docker rm front && sudo docker run -d --name front -p 8081:80 piedfront'


